### PR TITLE
Bug Fix: change MavenInvokerBuilder class to better test

### LINKED ISSUE #23: Change and add function of MavenInvokerBuilder
To help the testing property be implemented, two things need to be changed in MavenInvokerBuilder
1. the command should be "test" instead of just building the project
2. a boolean result needed, and then we can set corresponding status

### PR DESCRIPTION
**Pull request by Tian0602**
Fix the bugs in MavenInvokerBuilder and change the test correspondingly
Fix #23

### CODE REVIEW

**Review by Frequinzy — APPROVED** [review]
LGTM

File: DD2480-CI/src/main/java/mavenBuilder/MavenInvokerBuilder.java [hunk 1]
```diff
@@ -3,14 +3,16 @@
 import java.io.File;
 import java.io.InputStream;
 import java.util.Arrays;
+import java.util.Collections;
 import java.util.List;
 
 import org.apache.maven.shared.invoker.*;
 
 public class MavenInvokerBuilder {
```
Comment (LottaJohnsson) [inline DD2480-CI/src/main/java/mavenBuilder/MavenInvokerBuilder.java:11]: You should probably add some documentation here just saying what the class does. Otherwise it looks good to me!

**Review by LottaJohnsson — APPROVED** [review]
LGTM!
